## Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Minecraft Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.1,1.22)
neo_version=21.4.157
neo_version_range=[21,)
loader_version_range=[4,)

## Mod Properties
mod_id=auxiliautilities
mod_name=Auxilia Utilities
mod_license=MIT
mod_version=1.0.0
mod_group_id=fr.iglee42
mod_authors=iglee42
mod_description=A port of Extra Utilities 2 to newer version of Minecraft.

## Dependency Properties
lib_version=1.2.7
lib_version_range=[1.2.7,)
jei_version=20.0.0.4
curios_version=10.0.1